version: '3'

services:
  poker-master-tool:
    build: ./
    image: poker-master-tool
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes: 
      - ./logs:/usr/src/app/logs