version: '3'

services:
  poker-master-tool:
    build:
      context: .
      args:
        - NODE_ENV=development
    image: poker-master-tool
    restart: always  
    ports:
      - "3000:3000"
    volumes: 
      - ./logs:/usr/src/app/logs