name: Deploy
on:
  workflow_run:
    workflows: Build and run tests
    branches: main
    types: completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Connect via SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.SSH_BUILD_PATH }}
          git fetch
          git reset --hard origin/main
          cd ../..
          docker-compose up -d --build poker-master-tool
